Устинов - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #110
Opened 2023-04-29 15:50 UTC by UAlex322

2023-04-29 16:12 UTC, UAlex322 commented
@FirstStep0, @Dnoniel-Ermolaev, прошу поучаствовать в code review.

2023-04-29 16:39 UTC, Dnoniel-Ermolaev requested changes
Отличные комментарии!
Добавь, пожалуйста, тест на проверку корректности алгоритма на одноэлементном массиве.
И ещё проверь свой алгоритм на отрицательных и смешанных значениях!

2023-04-29 19:13 UTC, FirstStep0 commented
Добавь, пожалуйста, тест со значениями std::numeric_limits<int>::min(), std::numeric_limits<int>::max()

2023-04-29 19:19 UTC, FirstStep0 requested changes
Добавь, пожалуйста, тест со значениями std::numeric_limits::min(), std::numeric_limits::max()

2023-04-30 08:54 UTC, UAlex322 commented
> Отличные комментарии! Добавь, пожалуйста, тест на проверку корректности алгоритма на одноэлементном массиве. И ещё проверь свой алгоритм на отрицательных и смешанных значениях!

Добавил тесты.

2023-04-30 08:54 UTC, UAlex322 commented
> Добавь, пожалуйста, тест со значениями std::numeric_limits::min(), std::numeric_limits::max()

Пофиксил алгоритм и добавил соответствующие тесты.

2023-04-30 09:15 UTC, Dnoniel-Ermolaev approved these changes

2023-04-30 14:15 UTC, FirstStep0 approved these changes

2023-04-30 16:42 UTC, merged