Кудряшов - Лабораторная работа #1
Teddy-Hackers/devtools-course-practice pull request #151
Opened 2023-05-02 17:28 UTC by TiaYeah

2023-05-02 18:18 UTC, TiaYeah commented
@wellcome2AD @UvarkinIlya Проверьте пожалуйста

2023-05-02 20:08 UTC, wellcome2AD requested changes

2023-05-02 20:08 UTC, wellcome2AD commented on modules/complex-number/test/test_KUDRYASHOV_NIKITA_complex_number.cpp
> +    EXPECT_EQ(num1 == num2, true);
EXPECT_EQ(num1, num2);

2023-05-02 20:08 UTC, wellcome2AD commented on modules/complex-number/test/test_KUDRYASHOV_NIKITA_complex_number.cpp
> +    EXPECT_EQ(num1 != num2, true);
EXPECT_NE(num1, num2);

2023-05-04 14:21 UTC, wellcome2AD approved these changes
Всё ок

2023-05-04 20:09 UTC, UvarkinIlya approved these changes

2023-05-04 23:09 UTC, SigachevAV approved these changes
OK_KO

2023-05-04 23:09 UTC, merged