Попов - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #166
Opened 2023-05-08 14:04 UTC by navys00

2023-05-08 20:40 UTC, navys00 commented
@AlPashina  @danielbulgakov  запрашиваю резюме, пожалуйста

2023-05-08 21:07 UTC, navys00 commented
@AlPashina @danielbulgakov запрашиваю резюме, пожалуйста

2023-05-08 21:11 UTC, AlPashina requested changes
Можно было бы поменять тип параметров на вещественное число, чтобы повысить точность вычислений

2023-05-08 21:28 UTC, AlPashina approved these changes
Всё вроде ок)

2023-05-09 07:47 UTC, navys00 commented
@danielbulgakov

2023-05-09 08:35 UTC, danielbulgakov approved these changes
🐐

2023-05-12 06:55 UTC, merged