Уваркин - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #172
Opened 2023-05-11 04:23 UTC by UvarkinIlya

2023-05-12 08:27 UTC, dkurt commented
ping bot

2023-05-13 09:02 UTC, UvarkinIlya commented
@mk101 @srselivan посмотрите  pr пж

2023-05-13 09:12 UTC, mk101 requested changes

2023-05-13 09:12 UTC, mk101 commented on modules/sets/include/set.h
> +    explicit Set(const std::vector<int> &elems) : elems(elems) {}
Я бы оставил один конструктор
```c++
explicit Set(const std::vector<int> &elems = {}) : elems(elems) {}
```

2023-05-13 09:12 UTC, mk101 commented on modules/sets/src/set.cpp
> +}
Лучше возвращать `bool`
```c++
std::find(elems.begin(), elems.end(), elem) != elems.end();
```

2023-05-13 09:12 UTC, srselivan approved these changes

2023-05-13 09:31 UTC, mk101 approved these changes
👍

2023-05-27 16:37 UTC, merged