Микерин и Булгаков. Лабораторная работа №3
Teddy-Hackers/devtools-course-practice pull request #22
Opened 2023-04-20 18:19 UTC by Ilya837

2023-04-22 12:05 UTC, dkurt requested changes
Шифр Виженера занят https://github.com/Teddy-Hackers/devtools-course-practice/pull/11

2023-04-27 08:39 UTC, Ilya837 commented on lab-guide/topics.md
> +| Шифр Виженера ||Микерин Илья и Даниил Булгаков 382008-1|
А разве 3 лаба не должна выполняться в команде ?

2023-04-27 08:51 UTC, dkurt commented on lab-guide/topics.md
> +| Шифр Виженера ||Микерин Илья и Даниил Булгаков 382008-1|
Нет

2023-04-27 08:53 UTC, dkurt commented on lab-guide/topics.md
> +| Шифр Виженера ||Микерин Илья и Даниил Булгаков 382008-1|
Если хотите вместе - делайте что-то подобное:
| lab name | lab 2 | lab 3 |
|---|----|---|
| lab topic 1 | student 1 | student 2 |
| lab topic 2 | student 2 | student 1|

2023-04-27 09:03 UTC, Ilya837 commented on lab-guide/topics.md
> +| Шифр Виженера ||Микерин Илья и Даниил Булгаков 382008-1|
Тогда 2 вопроса:
1) по итогу я буду делать 3-ю Лабу по его теме, а он по моей?
2) можно-ли выбирать одинаковую тему на 2 и 3 лабы?

2023-04-27 09:06 UTC, dkurt commented on lab-guide/topics.md
> +| Шифр Виженера ||Микерин Илья и Даниил Булгаков 382008-1|
@Ilya837, а в чем тогда будет результат индивидуальной работы? Нет, одна ячейка в таблице - одно имя

2023-04-28 04:24 UTC, dkurt commented
Fix conflict

2023-04-28 09:09 UTC, dkurt approved these changes

2023-04-28 12:55 UTC, dkurt commented
see https://github.com/Teddy-Hackers/devtools-course-practice/pull/87

2023-04-28 12:55 UTC, closed without merging