Костерин - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #220
Opened 2023-05-17 11:03 UTC by korgi12005

2023-05-19 07:36 UTC, korgi12005 commented
review

2023-05-19 07:38 UTC, imterinaa approved these changes
NICE!

2023-05-19 07:40 UTC, mk101 requested changes

2023-05-19 07:40 UTC, mk101 commented on modules/code_vijener/include/code_vijener.h
> +  std::string GetCodeStr();
Лучше возвращать константную ссылку и сделать сам метод константным

2023-05-19 08:38 UTC, mk101 approved these changes
👍

2023-05-20 11:46 UTC, TupoaMudille approved these changes

2023-05-20 11:47 UTC, merged