Миронов - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #255
Opened 2023-05-25 18:17 UTC by onkelzeddy

2023-05-26 08:31 UTC, StJi requested changes

2023-05-26 08:31 UTC, StJi commented on modules/interpolation_search/include/interpolation-search.h
Может стоит назвать файл через нижнее подчёркивание? чтобы во всех файлах было одинаковый стиль

2023-05-26 08:31 UTC, StJi commented on modules/interpolation_search/test/test_interpolation_search.cpp
Хочется увидеть тесты с массивами отрицательных чисел и смешанными массивами

2023-05-26 08:31 UTC, StJi commented on modules/interpolation_search/test/test_interpolation_search.cpp
Еще хочется тесты, в которых искомое число повторяется

2023-05-28 10:22 UTC, StJi approved these changes
Good

2023-05-28 12:18 UTC, TupoaMudille approved these changes

2023-05-28 12:18 UTC, merged