Lapin tests for lab1
Teddy-Hackers/devtools-course-practice pull request #258
Opened 2023-05-26 06:56 UTC by dochkavurdalaka

Lapin Laba 1

2023-05-26 10:12 UTC, Dnoniel-Ermolaev requested changes
Добавь пожалуйста тесты на создание чисто мнимого числа и числа с целой частью.

2023-05-28 14:40 UTC, nik-se0 commented
Стоит добавить тест с проверкой вычитания комплексных чисел

2023-05-28 16:03 UTC, nik-se0 approved these changes

2023-05-28 16:07 UTC, Dnoniel-Ermolaev approved these changes

2023-05-28 18:00 UTC, merged