Шипилов - Лабораторная работа #3
Teddy-Hackers/devtools-course-practice pull request #261
Opened 2023-05-26 18:05 UTC by artemchikk

2023-05-27 06:56 UTC, AleksandrEremin requested changes

2023-05-27 06:56 UTC, AleksandrEremin commented on modules/polynomial_calculator/src/polynomial_calculator_application.cpp
> +
Привет! Думаю, можно вместо x и z указать более информативные названия, чтобы пользователь мог понять что нужно вводить

2023-05-27 13:05 UTC, Dnoniel-Ermolaev requested changes

2023-05-27 13:05 UTC, Dnoniel-Ermolaev commented on modules/polynomial_calculator/src/polynomial_calculator_application.cpp
> +        help(argv[0], "ERROR: invalid number of arguments.\n\n");
Лишние проверки. Просто rgc != 8

2023-05-27 13:17 UTC, Dnoniel-Ermolaev approved these changes

2023-05-27 17:12 UTC, AleksandrEremin approved these changes

2023-05-28 12:19 UTC, TupoaMudille approved these changes

2023-05-28 12:19 UTC, merged