Кандрин - Лабораторная работа #1
Teddy-Hackers/devtools-course-practice pull request #29
Opened 2023-04-21 10:33 UTC by akandrin

2023-04-21 20:15 UTC, akandrin commented
> Лабораторная работа 1.
> Рецензия кода.
> ... необходимо пройти ревью кода от двух своих сокурсников. Пригласите их к дискуссии, добавив в pull reqeust комментарий вида @github-name
> Рецензия считается незавершенной, пока вы не получите два approve (Pull Request -> File changed -> Review changes -> Approve -> Submit review) от коллег. 

@srselivan @mk101 Коллеги, день добрый. Запрашиваю ревью.

2023-04-22 12:06 UTC, mk101 approved these changes
Все ок

2023-04-22 12:07 UTC, srselivan approved these changes
Всё ок

2023-04-22 12:10 UTC, dkurt requested changes

2023-04-22 12:10 UTC, dkurt commented on modules/complex-number/test/test_KANDRIN_ALEXEY_complex_number.cpp
> +    EXPECT_EQ(z, z_copy);
There is no check that numbers passed by constructor made valid complex number. Check not only z equals z_copy but getRe, getIm matches 5 and -7 correspondingly.

2023-04-22 15:37 UTC, akandrin commented on modules/complex-number/test/test_KANDRIN_ALEXEY_complex_number.cpp
> +    EXPECT_EQ(z, z_copy);
Исправлено

2023-04-22 15:45 UTC, dkurt approved these changes

2023-04-22 17:06 UTC, akandrin commented
@dkurt Здравствуйте. Что-то ещё требуется для мержа?

2023-04-23 17:50 UTC, merged