Воронов-лабораторная №2
Teddy-Hackers/devtools-course-practice pull request #303
Opened 2023-06-04 15:25 UTC by GerchVAM

2023-06-04 15:40 UTC, GoncharovaAnna approved these changes
Okok

2023-06-05 17:46 UTC, SigachevAV commented
Данная тема занята и занята не вами. Выбирайте другую.

2023-06-07 15:45 UTC, dkurt commented
Подтверждаю, что случилась накладка при выборе тем. Проверю данную лабораторную на плагиат и если всё ок, то приму PR.

2023-06-07 15:48 UTC, dkurt commented on modules/voronov_a_k_combs/test/test_combs.cpp
> +}
Добавьте проверку на сами комбинации, а не только из количество.

2023-06-07 15:53 UTC, dkurt commented on modules/voronov_a_k_combs/include/combs.h
> +};
Не понимаю, как работает ваш класс, если чесно. Сделайте осмысленные названия методов и аргументов.

Помните, что цель задачи - выдать всемозвожные комбинации из N по K. Например:
дан массив (112, 18, -4, 9) и число k = 3. Результат:
(количество сочетаний из 4 по 3 это 4! / [ (4 - 3)! * 3! ] = 24 / 6 = 4
```
112, 18, 9
112, 18, -4
112, -4, 9
18, -4, 9
```

2023-06-07 15:53 UTC, dkurt requested changes
Не понимаю, как работает ваш класс, если честно. Сделайте осмысленные названия методов и аргументов.

Помните, что цель задачи - выдать всемозвожные комбинации из N по K. Например:
дан массив (112, 18, -4, 9) и число k = 3. Результат:
(количество сочетаний из 4 по 3 это 4! / [ (4 - 3)! * 3! ] = 24 / 6 = 4
```
112, 18, 9
112, 18, -4
112, -4, 9
18, -4, 9
```

2023-10-25 14:53 UTC, closed without merging