Селиванкин - Лабораторная работа #1
Teddy-Hackers/devtools-course-practice pull request #33
Opened 2023-04-21 16:54 UTC by srselivan

2023-04-22 12:14 UTC, srselivan commented
@akandrin, @mk101 запрашиваю ревью

2023-04-22 12:16 UTC, mk101 approved these changes
Все ок

2023-04-22 12:48 UTC, akandrin requested changes

2023-04-22 12:48 UTC, akandrin commented on modules/complex-number/test/test_SELIVANKIN_SERGEY_complex_number.cpp
> +    bool isEqual = a != b;
Может быть, `isNotEqual`?

2023-04-22 13:11 UTC, akandrin approved these changes
ок

2023-04-22 14:20 UTC, dkurt commented on modules/complex-number/test/test_SELIVANKIN_SERGEY_complex_number.cpp
> +    EXPECT_TRUE(isEqual);
Use expect_eq

2023-04-22 14:20 UTC, dkurt commented on modules/complex-number/test/test_SELIVANKIN_SERGEY_complex_number.cpp
> +}
Expect_ne

2023-04-22 14:22 UTC, dkurt commented on modules/complex-number/test/test_SELIVANKIN_SERGEY_complex_number.cpp
> +    ASSERT_EQ(expected, result);
Not reliable test in case operator= may always return true. Use getIm, gerRe

2023-04-23 12:15 UTC, dkurt commented on modules/complex-number/test/test_SELIVANKIN_SERGEY_complex_number.cpp
> +    ComplexNumber expected(5.0, 5.0);
make different values

2023-04-23 12:16 UTC, dkurt commented on modules/complex-number/test/test_SELIVANKIN_SERGEY_complex_number.cpp
> +    double im = 0.0;
Choose non-zero different values.

2023-04-25 10:01 UTC, dkurt approved these changes

2023-04-27 05:20 UTC, TupoaMudille approved these changes
ok

2023-04-27 05:21 UTC, merged