Колесов - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #36
Opened 2023-04-22 14:25 UTC by mk101

2023-04-22 19:08 UTC, mk101 commented
@akandrin, @srselivan, запрашиваю ревью

2023-04-22 19:17 UTC, srselivan reviewed
Можно добавить `operator=`

2023-04-22 19:53 UTC, akandrin requested changes

2023-04-22 19:53 UTC, akandrin commented on modules/caesar-cipher/include/cipher.h
> +  bool foreignChars = true;
Возможно, было бы удобнее завести конструктор `Kernel(uint32_t shift, const std::string & alphabet = "abcdefghijklmnopqrstuvwxyz", bool foreignChars = true /*или false*/)`, а также оператор присваивания

И ниже вместо конструкций вида
```
Kernel kernel;
kernel.alphabet = "abc";
kernel.shift = 7;
```
Можно будет писать `Kernel kernel(7, "abc");`

2023-04-22 19:53 UTC, akandrin commented on modules/caesar-cipher/include/cipher.h
> +  CaesarCipher &operator=(const CaesarCipher &c) = default;
Тогда уж, руководствуясь [правилом пяти](https://ru.wikipedia.org/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE_%D1%82%D1%80%D1%91%D1%85_(C%2B%2B)#%D0%9F%D1%80%D0%B0%D0%B2%D0%B8%D0%BB%D0%BE_%D0%BF%D1%8F%D1%82%D0%B8), надо добавить и оператор присваивания перемещением

2023-04-22 19:53 UTC, akandrin commented on modules/caesar-cipher/test/test_cipher.cpp
> +  EXPECT_TRUE(check);
Здесь и ниже надо заменить
```
bool check = k == e;
EXPECT_TRUE(check);
```
на `EXPECT_EQ(k, e);`, и 
```
bool check = k != e;
EXPECT_TRUE(check);
```
на `EXPECT_NE(k, e);`

2023-04-23 08:21 UTC, akandrin approved these changes
Ок

2023-04-23 08:25 UTC, srselivan approved these changes
Всё ок

2023-04-27 05:24 UTC, merged