Кандрин - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #37
Opened 2023-04-22 14:33 UTC by akandrin

2023-04-22 16:22 UTC, akandrin commented
@mk101 @srselivan Коллеги, добрый день. Запрашиваю ревью.

> ВНИМАНИЕ, РЕЦЕНЗЕНТЫ: как бы прекрасно ни была сделана лабораторная, вы обязаны попросить какой-нибудь ее доработки. В лучшем случае это будут найденные вами баги, как минимум -- какие-то другие мелкие запросы, например переименование или изменение форматирования. Но вы обязаны оправить автора что-то доделать, чтобы он добавил коммитов и пулл-реквест прошел еще одно тестирование.

2023-04-22 17:06 UTC, mk101 requested changes
Стоит добавить метод clear для очистки стека.

2023-04-22 17:39 UTC, mk101 approved these changes
👍

2023-04-22 18:03 UTC, srselivan reviewed
Было бы неплохо добавить метод `size()` для стека

2023-04-22 19:06 UTC, srselivan approved these changes
👍

2023-04-23 18:33 UTC, akandrin commented
> Когда вы добьетесь "зеленого" билда, необходимо получить одобрение от двух сокурсников в виде approve. После этого пригласите на проверку интеграционных менеджеров.

@SigachevAV День добрый. Это Вы интеграционный менеджер? Если да, то два аппрува от сокурсников присутствуют, приглашаю на проверку :)

2023-04-23 21:02 UTC, SigachevAV approved these changes
всё вроде ок

2023-04-23 21:02 UTC, merged