Селиванкин - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #47
Opened 2023-04-23 11:19 UTC by srselivan

2023-04-25 19:21 UTC, mk101 requested changes

2023-04-25 19:21 UTC, mk101 commented on modules/binary-search/include/binary_search.h
> +    BinarySearch() = default;
Какой смысл от пустого конструктора, если массив обязательно нужен для поиска

2023-04-25 19:21 UTC, mk101 commented on modules/binary-search/include/binary_search.h
> +    void setNumbers(const std::vector<int>& _numbers);
Стоит добавить геттер

2023-04-25 19:21 UTC, mk101 commented on modules/binary-search/src/binary_search.cpp
> +int BinarySearch::find(const int& target) {
Какой смысл от ссылки, если размеры либо равны, либо ссылка даже весит больше

2023-04-25 19:21 UTC, mk101 commented on modules/binary-search/src/binary_search.cpp
> +    int right = static_cast<int>(numbers.size()) - 1;
Лучше наверное использовать `size_t` для индексов

2023-04-25 20:40 UTC, akandrin requested changes

2023-04-25 20:40 UTC, akandrin commented on modules/binary-search/test/test_binary_search.cpp
> +}
Может, в тесте проверять, что класс корректно находит каждый элемент массива?

```
std::vector<int> arr = {1, 2, 3, 4, 5, 6};
BinarySearch binarySearch(arr)
for (size_t i = 0; i < arr.size(); ++i)
{
  ASSERT_EQ(i, binarySearch.find(arr[i]));
}
```

2023-04-29 07:49 UTC, mk101 approved these changes
👍

2023-04-29 08:45 UTC, akandrin requested changes

2023-04-29 08:45 UTC, akandrin commented on modules/binary-search/src/binary_search.cpp
> +    std::size_t right = numbers.size() - 1;
Для пустых массивов функция не будет работать (потому что `size_t` беззнаковый).

Чтобы избежать этого, можно в начало функции добавить
```
if (numbers.empty())
  return -1;
```

2023-04-29 08:58 UTC, srselivan commented on modules/binary-search/src/binary_search.cpp
> +    std::size_t right = numbers.size() - 1;
А зачем тогда этот `size_t` нужен, если проще играться с `int`. Тем более я возвращаю `size_t`, и -1 превратится в большое число

2023-04-29 09:54 UTC, akandrin commented on modules/binary-search/src/binary_search.cpp
> +    std::size_t right = numbers.size() - 1;
> А зачем тогда этот size_t нужен, если проще играться с int

Исторически сложилось, что для индексации используется тип `size_t`. Его размер равен размеру указателя, так что с помощью переменной типа `size_t` можно проиндексировать настолько большой массив, насколько большой массив вообще возможен.

В случае с `int` - его размер на x64 равен всего 4 байта, и его максимальное значение = 2147483647. То есть с его помощью можно проиндексировать массив `std::vector<char>` размером в 2 гигабайта. Но если создать массив размером в 2 гигабайта + 1 байт, то этот последний байт уже нельзя будет проиндексировать (он будет за границей диапазона `int`).

Вот для таких (не высосанных из пальца) ситуаций и используют тип `size_t` :)

> Тем более я возвращаю size_t, и -1 превратится в большое число

Да, и это нормальная ситуация.  Так же поступают разработчики стандартной библиотеки C++. `(size_t)-1` выступает в роли невалидного индекса. Например, это использует [`std::string::npos`](https://en.cppreference.com/w/cpp/string/basic_string/npos)

2023-04-29 09:56 UTC, akandrin approved these changes
ok

2023-04-29 10:03 UTC, srselivan commented on modules/binary-search/src/binary_search.cpp
> +    std::size_t right = numbers.size() - 1;
спасибо, так понятнее

2023-04-29 21:07 UTC, merged