Юрин - Лабораторная работа 1
Teddy-Hackers/devtools-course-practice pull request #49
Opened 2023-04-23 12:52 UTC by Blighting

2023-04-23 13:05 UTC, Blighting commented
@dkurt Здравствуйте. Пробовал различные комбинации тестов, всегда валится Code Coverage. В чем может быть проблема?

2023-04-23 15:19 UTC, dkurt commented
@Blighting , ошибка компиляции:

```
/home/runner/work/devtools-course-practice/devtools-course-practice/modules/complex-number/test/test_Yurin_Evgeny_complex_number.cpp:36:5: error: expected constructor, destructor, or type conversion before ‘(’ token
   36 | Test(Yurin_Evgeny_ComplexNumberTest, Test_Set) {
```

2023-04-23 15:47 UTC, Blighting commented
@srselivan  @danielbulgakov Привет ребята, посмотрите пожалуйста.

2023-04-23 15:59 UTC, srselivan requested changes

2023-04-23 15:59 UTC, srselivan commented on modules/complex-number/test/test_Yurin_Evgeny_complex_number.cpp
> +TEST(Yurin_Evgeny_ComplexNumberTest, Test_minus) {
Может `Test_Substraction`?

2023-04-23 15:59 UTC, srselivan commented on modules/complex-number/test/test_Yurin_Evgeny_complex_number.cpp
> +  number.setRe(5.0);
Не лучше ли подставлять в `setIm()` и `getRe()` переменные `expectedIm` и `expectedRe`?

2023-04-23 16:04 UTC, srselivan approved these changes
👍

2023-04-23 16:10 UTC, danielbulgakov approved these changes
👍

2023-04-23 16:15 UTC, Blighting commented
@dkurt Работа готова к финальному ревью

2023-04-25 10:17 UTC, dkurt approved these changes

2023-04-27 05:26 UTC, TupoaMudille approved these changes
ok

2023-04-27 05:26 UTC, merged