Уваркин - Лабораторная работа #1
Teddy-Hackers/devtools-course-practice pull request #76
Opened 2023-04-27 21:11 UTC by UvarkinIlya

2023-04-27 21:45 UTC, UvarkinIlya commented
@wellcome2AD  @srselivan прощу ревью

2023-04-28 04:32 UTC, srselivan requested changes

2023-04-28 04:32 UTC, srselivan commented on modules/complex-number/test/test_UVARKIN_ILYA_complex_number.cpp
> +// Copyright 2023 ILYA UVARKIN
Может не капсом лучше будет?

2023-04-28 04:32 UTC, srselivan commented on modules/complex-number/test/test_UVARKIN_ILYA_complex_number.cpp
> +  ASSERT_EQ(rez.getIm(), 42);
Может `result`, а не `rez`?

2023-04-28 04:32 UTC, srselivan commented on modules/complex-number/test/test_UVARKIN_ILYA_complex_number.cpp
> +}
Не понял зачем этот тест, если ты до этого проверяешь сумму по компонентам.

2023-04-29 22:24 UTC, wwoffxx approved these changes

2023-04-30 13:37 UTC, UvarkinIlya commented
@mk101

2023-04-30 13:38 UTC, mk101 approved these changes
👍

2023-04-30 14:03 UTC, merged