Ивлев - Лабораторная работа #1
Teddy-Hackers/devtools-course-practice pull request #85
Opened 2023-04-28 08:47 UTC by Faert

2023-04-28 08:50 UTC, dkurt commented
Закрою-открою PR для проверки бота

2023-04-28 16:00 UTC, UAlex322 commented
Извиняюсь за поздний ответ. Все представленные тесты понятны. Можно, при желании, добавить тесты для арифметических операций.

2023-04-29 09:54 UTC, Dnoniel-Ermolaev requested changes
Доброго дня. Можно было бы добавить  тесты на проверку конструктора по умолчанию.

2023-04-29 10:47 UTC, Dnoniel-Ermolaev approved these changes

2023-04-29 10:55 UTC, UAlex322 approved these changes

2023-04-29 18:00 UTC, merged