Коробейникова - Лабораторная работа #2
Teddy-Hackers/devtools-course-practice pull request #94
Opened 2023-04-28 13:21 UTC by wellcome2AD

2023-04-28 13:49 UTC, wellcome2AD commented
@akandrin , @TibidoX пришлите ревью, пожалста

2023-04-28 14:01 UTC, akandrin requested changes

2023-04-28 14:01 UTC, akandrin commented on modules/point-falls-into-a-triangle/test/test_point-falls-into-a-triangle.cpp
> +TEST(Default, ParametrizedConstructor) {
Надо поменять название набора тестов с `Default` на что-то более осмысленное

2023-04-28 14:35 UTC, akandrin approved these changes

2023-04-29 17:22 UTC, TibidoX approved these changes
Very nice!

2023-04-29 17:26 UTC, wellcome2AD commented
@SigachevAV merge please

2023-04-29 21:08 UTC, merged