Коробейникова - Лабораторная работа #3
Teddy-Hackers/devtools-course-practice pull request #99
Opened 2023-04-28 20:12 UTC by wellcome2AD

2023-04-28 20:13 UTC, wellcome2AD commented
@akandrin , @srselivan откройте букву Р, откройте букву Е, откройте букву В. назовёте всё слово сразу или играем дальше?

2023-04-29 08:03 UTC, wellcome2AD commented
@akandrin , @TibidoX прошу ревью

2023-04-29 08:55 UTC, akandrin requested changes

2023-04-29 08:55 UTC, akandrin commented on lab-guide/topics.md
> +| Стэк | Кандрин А. 382008-1 |Коробейникова А. 382008-1|
Этого изменения здесь быть не должно (поскольку оно уже было добавлено ранее здесь https://github.com/Teddy-Hackers/devtools-course-practice/pull/95/files )

2023-04-29 08:55 UTC, akandrin commented on modules/stack/src/stack_app.cpp
> +      if (*argv[i] != '\0') {
А как может случиться, что `*argv[i] == '\0'`? И почему нас это устраивает?

Кажется, тут должно быть просто
```
} else {
  message += "error: unknown key " + key;
}
```

2023-04-29 08:55 UTC, akandrin commented on modules/stack/src/stack_app.cpp
> +#include <sstream>
Этот инклюд используется?

2023-04-29 15:38 UTC, akandrin approved these changes
ок

2023-04-30 14:14 UTC, TibidoX approved these changes
Nice!

2023-04-30 16:42 UTC, merged